# Generated by Django 5.1 on 2024-08-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='unidad_medida',
            field=models.CharField(choices=[('KG', 'Kilogramos'), ('G', 'Gramos'), ('L', 'Litros'), ('Ud', 'Unidad')], default='Ud', max_length=2),
        ),
    ]
