# Generated by Django 5.1 on 2024-09-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_detallepedido_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='en_proceso',
            field=models.BooleanField(default=False),
        ),
    ]
