# Generated by Django 5.1 on 2024-08-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_inventario_unidad_medida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='contacto',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contact_method',
            field=models.CharField(choices=[('cel_tel', 'Cel/Tel'), ('email', 'Email')], default='cel_tel', max_length=10),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_proveedor',
            field=models.CharField(max_length=255),
        ),
    ]
