# Generated by Django 5.1 on 2024-09-02 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_pedido_en_proceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='usuario_procesando',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_en_proceso', to=settings.AUTH_USER_MODEL),
        ),
    ]
