# Generated by Django 5.1 on 2024-09-12 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_mensaje_chat_mensaje_destinatarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='destinatarios',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='remitente',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
