# Generated by Django 5.1 on 2024-11-26 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_transaccioncaja_pago'),
        ('restaurant', '0005_alter_pedido_estado'),
    ]

    operations = [
    ]
