# Generated by Django 5.1 on 2024-09-12 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_chat_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='chat',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='destinatarios',
            field=models.ManyToManyField(related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL),
        ),
    ]
