# Generated by Django 5.1 on 2024-08-30 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_pago_comprobante'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
