# Generated by Django 5.1 on 2024-09-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_remove_mensaje_chat_mensaje_destinatarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='nombre',
            field=models.CharField(default='Chat General', max_length=255),
        ),
    ]
