# Generated by Django 5.1 on 2024-08-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
