# Generated by Django 5.1 on 2024-08-31 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_menu_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccioncaja',
            name='pago',
            field=models.ForeignKey(blank=True, help_text='Pago asociado a esta transacción, si corresponde.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='restaurant.pago'),
        ),
        migrations.AlterField(
            model_name='transaccioncaja',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='restaurant.caja'),
        ),
    ]
