# Generated by Django 5.1 on 2024-08-31 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_transaccioncaja_pago_alter_transaccioncaja_caja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccioncaja',
            name='pago',
        ),
    ]
